import React, { useState, useEffect, useCallback, useRef } from "react";
import {
	Dialog,
	DialogTitle,
	DialogContent,
	DialogActions,
	Button,
	Box,
	Typography,
	CircularProgress,
	Alert,
	Chip,
	Divider,
} from "@mui/material";
import {
	CheckCircle as SuccessIcon,
	Error as ErrorIcon,
	Refresh as RefreshIcon,
} from "@mui/icons-material";
import { QRCodeSVG } from "qrcode.react";
import { useAuth } from "../../../auth/AuthContext";
import { apiCall } from "../../../api/api";
import {
	paymentCreatePayment,
	paymentGetPaymentRequest,
	paymentVerifyPayment,
} from "../../../api/urls";
import type { InvoiceDetail, PaymentLinkResponse } from "../../../types/Invoice";

interface PaymentMethod {
	paymentMethodId: number;
	methodCode: string;
	methodName: string;
}

interface PaymentQRModalProps {
	open: boolean;
	onClose: () => void;
	invoice: InvoiceDetail;
	onPaymentSuccess: () => void;
	role?: string;
	paymentMethod?: PaymentMethod | null;
}

type PaymentState = "loading" | "created" | "checking" | "success" | "error" | "cancelled";

const PaymentQRModal: React.FC<PaymentQRModalProps> = ({
	open,
	onClose,
	invoice,
	onPaymentSuccess,
	role = "receptionist",
	paymentMethod,
}) => {
	const { token, user } = useAuth();
	const [paymentState, setPaymentState] = useState<PaymentState>("loading");
	const [paymentLink, setPaymentLink] = useState<PaymentLinkResponse | null>(null);
	const [error, setError] = useState<string | null>(null);
	const [countdown, setCountdown] = useState(0);
	const checkIntervalRef = useRef<NodeJS.Timeout | null>(null);
	const countdownIntervalRef = useRef<NodeJS.Timeout | null>(null);

	const formatCurrency = (amount: number) => {
		return new Intl.NumberFormat("vi-VN", {
			style: "currency",
			currency: "VND",
		}).format(amount);
	};

	// Payment description format: HD{invoiceId} (e.g., HD41)
	// Generated by backend and returned in paymentLink.description
	// QR code is provided directly by PayOS in paymentLink.qrCode or paymentLink.checkoutUrl

	const clearIntervals = useCallback(() => {
		if (checkIntervalRef.current) {
			clearInterval(checkIntervalRef.current);
			checkIntervalRef.current = null;
		}
		if (countdownIntervalRef.current) {
			clearInterval(countdownIntervalRef.current);
			countdownIntervalRef.current = null;
		}
	}, []);

	const createPaymentLink = useCallback(() => {
		setPaymentState("loading");
		setError(null);

		const staffId = (user as any)?.staffId || 1;
		// CRITICAL: Description MUST NOT contain spaces for Viettel Money & VietQR compatibility
		// Format: HD{invoiceId} (e.g., HD41) - alphanumeric only, no spaces
		const requestBody = JSON.stringify({
			invoiceId: invoice.invoiceId,
			staffId: staffId,
			description: `HD${invoice.invoiceId}`,
			returnUrl: window.location.href,
			cancelUrl: window.location.href,
		});

		apiCall(
			paymentCreatePayment(role),
			"POST",
			token,
			requestBody,
			(response: { data: PaymentLinkResponse }) => {
				setPaymentLink(response.data);
				setPaymentState("created");
				// Set countdown for 15 minutes (900 seconds)
				setCountdown(900);
			},
			(err: any) => {
				console.error("Error creating payment link:", err);
				setError(err.message || "Failed to create payment link");
				setPaymentState("error");
			}
		);
	}, [invoice.invoiceId, token, role, user]);

	const checkPaymentStatus = useCallback(() => {
		if (!paymentLink) return;

		apiCall(
			paymentGetPaymentRequest(role, paymentLink.orderCode),
			"GET",
			token,
			null,
			(response: { data: any }) => {
				const status = response.data.status;
				console.log("Payment status check:", status); // Debug log
				if (status === "PAID") {
					clearIntervals();
					// Verify and update invoice
					setPaymentState("checking");

					const requestBody = JSON.stringify({
						orderCode: paymentLink.orderCode,
						invoiceId: invoice.invoiceId,
					});

					apiCall(
						paymentVerifyPayment(role),
						"POST",
						token,
						requestBody,
						() => {
							console.log("Payment verified successfully"); // Debug log
							setPaymentState("success");
							setTimeout(() => {
								onPaymentSuccess();
							}, 2000);
						},
						(err: any) => {
							console.error("Error verifying payment:", err);
							setError(err.message || "Failed to verify payment");
							setPaymentState("error");
						}
					);
				} else if (status === "CANCELLED" || status === "EXPIRED") {
					clearIntervals();
					setPaymentState("cancelled");
					setError("Payment was cancelled or expired");
				}
				// else keep checking
			},
			(err: any) => {
				console.error("Error checking payment status:", err);
			}
		);
	}, [paymentLink, token, role, clearIntervals, invoice.invoiceId, onPaymentSuccess]);

	// Effect to create payment link when modal opens
	useEffect(() => {
		if (open && invoice.paymentStatus !== "PAID") {
			createPaymentLink();
		}

		return () => {
			clearIntervals();
		};
	}, [open, invoice.paymentStatus, createPaymentLink, clearIntervals]);

	// Effect for auto-checking payment status
	useEffect(() => {
		if (paymentState === "created" && paymentLink) {
			// Check every 5 seconds
			checkIntervalRef.current = setInterval(checkPaymentStatus, 5000);

			// Countdown timer
			countdownIntervalRef.current = setInterval(() => {
				setCountdown((prev) => {
					if (prev <= 1) {
						clearIntervals();
						setPaymentState("cancelled");
						setError("Payment time expired");
						return 0;
					}
					return prev - 1;
				});
			}, 1000);
		}

		return () => {
			clearIntervals();
		};
	}, [paymentState, paymentLink, checkPaymentStatus, clearIntervals]);

	const handleClose = () => {
		clearIntervals();
		onClose();
	};

	const handleRetry = () => {
		createPaymentLink();
	};

	const formatTime = (seconds: number) => {
		const mins = Math.floor(seconds / 60);
		const secs = seconds % 60;
		return `${mins}:${secs.toString().padStart(2, "0")}`;
	};

	const renderContent = () => {
		switch (paymentState) {
			case "loading":
				return (
					<Box
						sx={{
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
							py: 4,
						}}
					>
						<CircularProgress />
						<Typography sx={{ mt: 2 }}>Creating payment QR code...</Typography>
					</Box>
				);

			case "created":
				return (
					<Box
						sx={{
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
						}}
					>
						{/* Payment Info */}
						<Box sx={{ width: "100%", mb: 3 }}>
							<Typography variant="body2" color="text.secondary">
								Invoice ID: #{invoice.invoiceId}
							</Typography>
							<Typography variant="h5" color="primary" sx={{ mt: 1 }}>
								{formatCurrency(paymentLink?.amount || invoice.totalAmount)}
							</Typography>
							{/* Order code */}
							<Box sx={{ mt: 1, p: 1, backgroundColor: "#e8f5e9", borderRadius: 1 }}>
								<Typography variant="body2" color="success.dark">
									Order Code: <strong style={{ fontFamily: 'monospace' }}>{paymentLink?.orderCode}</strong>
								</Typography>
							</Box>
							{/* Payment description */}
							<Box sx={{ mt: 1, p: 1, backgroundColor: "#e3f2fd", borderRadius: 1 }}>
								<Typography variant="body2" color="primary.dark">
									Ref Code: <strong style={{ fontFamily: 'monospace', letterSpacing: 1 }}>{paymentLink?.description || `HD${invoice.invoiceId}`}</strong>
								</Typography>
							</Box>
							{paymentMethod && (
								<Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
									Payment Method: <strong>{paymentMethod.methodName}</strong>
								</Typography>
							)}
						</Box>

						<Divider sx={{ width: "100%", mb: 3 }} />

						{/* PayOS QR Code - Use qrCode or checkoutUrl from PayOS response */}
						{paymentLink?.qrCode ? (
							<Box
								sx={{
									p: 2,
									backgroundColor: "white",
									borderRadius: 2,
									boxShadow: 2,
									mb: 2,
								}}
							>
								<QRCodeSVG
									value={paymentLink.qrCode}
									size={256}
									level="H"
									includeMargin={true}
								/>
							</Box>
						) : paymentLink?.checkoutUrl ? (
							<Box
								sx={{
									p: 2,
									backgroundColor: "white",
									borderRadius: 2,
									boxShadow: 2,
									mb: 2,
								}}
							>
								<QRCodeSVG
									value={paymentLink.checkoutUrl}
									size={256}
									level="H"
									includeMargin={true}
								/>
							</Box>
						) : (
							<Box
								sx={{
									p: 4,
									backgroundColor: "#f5f5f5",
									borderRadius: 2,
									mb: 2,
									textAlign: "center",
								}}
							>
								<Typography>
									Payment code: <strong>{paymentLink?.orderCode}</strong>
								</Typography>
								<Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
									Waiting for bank info...
								</Typography>
							</Box>
						)}

						<Typography variant="body2" sx={{ mb: 1 }}>
							Scan QR code to pay via banking app
						</Typography>

						{/* Bank Account Info (like TMS) */}
						{paymentLink?.accountNumber && (
							<Box sx={{ 
								width: "100%", 
								p: 2, 
								backgroundColor: "#f5f5f5", 
								borderRadius: 1, 
								mb: 2 
							}}>
								<Typography variant="body2" sx={{ mb: 0.5 }}>
									Bank: <strong>{paymentLink.accountName || "N/A"}</strong>
								</Typography>
								<Typography variant="body2" sx={{ mb: 0.5 }}>
									Account: <strong style={{ fontFamily: 'monospace' }}>{paymentLink.accountNumber}</strong>
								</Typography>
								<Typography variant="body2">
									Amount: <strong>{formatCurrency(paymentLink.amount)}</strong>
								</Typography>
								<Typography variant="body2" sx={{ mt: 0.5 }}>
									Description: <strong style={{ fontFamily: 'monospace' }}>{paymentLink.description}</strong>
								</Typography>
							</Box>
						)}

						{/* Countdown */}
						<Chip
							label={`Time remaining: ${formatTime(countdown)}`}
							color={countdown > 60 ? "primary" : "warning"}
							sx={{ mb: 2 }}
						/>

						{/* Auto-check status indicator */}
						<Box sx={{ display: "flex", alignItems: "center" }}>
							<CircularProgress size={16} sx={{ mr: 1 }} />
							<Typography variant="body2" color="text.secondary">
								Checking payment status...
							</Typography>
						</Box>
					</Box>
				);

			case "checking":
				return (
					<Box
						sx={{
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
							py: 4,
						}}
					>
						<CircularProgress />
						<Typography sx={{ mt: 2 }}>Verifying payment...</Typography>
					</Box>
				);

			case "success":
				return (
					<Box
						sx={{
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
							py: 4,
						}}
					>
						<SuccessIcon color="success" sx={{ fontSize: 80 }} />
						<Typography variant="h6" sx={{ mt: 2, color: "success.main" }}>
							Payment successful!
						</Typography>
						<Typography color="text.secondary">
							Invoice #{invoice.invoiceId} has been paid
						</Typography>
					</Box>
				);

			case "cancelled":
			case "error":
				return (
					<Box
						sx={{
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
							py: 4,
						}}
					>
						<ErrorIcon color="error" sx={{ fontSize: 80 }} />
						<Typography variant="h6" sx={{ mt: 2, color: "error.main" }}>
							{paymentState === "cancelled" ? "Payment failed" : "An error occurred"}
						</Typography>
						{error && (
							<Alert severity="error" sx={{ mt: 2, width: "100%" }}>
								{error}
							</Alert>
						)}
						<Button
							variant="contained"
							startIcon={<RefreshIcon />}
							onClick={handleRetry}
							sx={{ mt: 2 }}
						>
							Retry
						</Button>
					</Box>
				);

			default:
				return null;
		}
	};

	return (
		<Dialog
			open={open}
			onClose={handleClose}
			maxWidth="sm"
			fullWidth
			disableEscapeKeyDown={paymentState === "checking"}
		>
			<DialogTitle sx={{ textAlign: "center" }}>QR Code Payment</DialogTitle>
			<DialogContent>{renderContent()}</DialogContent>
			<DialogActions>
				{paymentState !== "success" && paymentState !== "checking" && (
					<Button onClick={handleClose}>Close</Button>
				)}
			</DialogActions>
		</Dialog>
	);
};

export default PaymentQRModal;
